title: REG Linux
description: Retro Emulation Gaming Linux community builds for SBCs, handhelds, and mini PCs.
baseurl: ""
url: "https://reglinux.org"
og_image: "/assets/images/reg_linux_logo.png"
markdown: kramdown
exclude:
  - download-source.html
collections:
  devices:
    output: true
    permalink: /download/:name/
plugins:
  - jekyll-sitemap
  - jekyll-feed
