site_name: REG Linux Wiki
site_description: Immutable Linux for retro gaming devices
site_url: https://wiki.reglinux.org
repo_url: https://github.com/REG-Linux/wiki
repo_name: REG-Linux/wiki
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 REG Linux Team
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
  - scheme: default
    primary: blue
    accent: light blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: light blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.expand
  - navigation.sections
  - search.suggest
  - search.highlight
  - content.code.copy
  - content.action.edit
nav:
- Home: index.md
- Getting Started: getting-started.md
- Architecture: architecture.md
- Consoles:
  - Capcom Home Arcade: sbcs/capcom-home-arcade.md
- Single-Board Computers:
  - Overview:
    - Catalog: sbcs/catalog.md
    - Allwinner Boards: sbcs/allwinner.md
    - Amlogic Boards: sbcs/amlogic.md
    - Broadcom Boards: sbcs/broadcom.md
    - Qualcomm Boards: sbcs/qualcomm.md
    - Mediatek Boards: sbcs/mediatek.md
    - Samsung Boards: sbcs/samsung.md
    - Rockchip Boards: sbcs/rockchip.md
  - Asus:
    - Asus Tinker Board S: sbcs/asus-tinker-board-s.md
  - Banana Pi:
    - Banana Pi M2S: sbcs/banana-pi-m2s.md
    - Banana Pi M2 Zero: sbcs/banana-pi-m2-zero.md
    - Banana Pi M4 Berry: sbcs/banana-pi-m4-berry.md
    - Banana Pi M5: sbcs/banana-pi-m5.md
    - Banana Pi M7: sbcs/banana-pi-m7.md
  - Beelink:
    - Beelink GT King: sbcs/beelink-gt-king.md
    - Beelink GT King Pro: sbcs/beelink-gt-king-pro.md
  - Firefly:
    - Firefly Station M2 ROC-RK3566 PC: sbcs/firefly-station-m2-roc-rk3566-pc.md
    - Firefly Station M3 ROC-RK3588S PC: sbcs/firefly-station-m3-roc-rk3588s-pc.md
    - Firefly Station P2 ROC-RK3568 PC: sbcs/firefly-station-p2-roc-rk3568-pc.md
  - Hardkernel:
    - Hardkernel Odroid C2: sbcs/hardkernel-odroid-c2.md
    - Hardkernel Odroid C4: sbcs/hardkernel-odroid-c4.md
    - Hardkernel Odroid M1: sbcs/hardkernel-odroid-m1.md
    - Hardkernel Odroid XU3/XU4: sbcs/hardkernel-odroid-xu3-xu4.md
  - Khadas:
    - Khadas Edge 2: sbcs/khadas-edge-2.md
    - Khadas VIM 1: sbcs/khadas-vim-1.md
    - Khadas VIM 1S: sbcs/khadas-vim-1s.md
    - Khadas VIM 2: sbcs/khadas-vim-2.md
    - Khadas VIM 3L: sbcs/khadas-vim-3l.md
    - Khadas VIM 3: sbcs/khadas-vim-3.md
    - Khadas VIM 4: sbcs/khadas-vim-4.md
  - Milk-V:
    - Milk-V Mars: sbcs/milk-v-mars.md
    - Milk-V Meles: sbcs/milk-v-meles.md
  - MQMaker MiQi: sbcs/mqmaker-miqi.md
  - FriendlyElec:
    - NanoPi K2: sbcs/nano-pi-k2.md
    - NanoPi M4V2: sbcs/nano-pi-m4v2.md
  - Orange Pi:
    - Orange Pi 800: sbcs/orange-pi-800.md
    - Orange Pi One: sbcs/orange-pi-one.md
    - Orange Pi One Plus: sbcs/orange-pi-one-plus.md
    - Orange Pi PC 2: sbcs/orange-pi-pc-2.md
    - Orange Pi PC: sbcs/orange-pi-pc.md
    - Orange Pi Plus 2E: sbcs/orange-pi-plus-2e.md
    - Orange Pi Zero 2: sbcs/orange-pi-zero-2.md
    - Orange Pi Zero 2W: sbcs/orange-pi-zero-2w.md
    - Orange Pi Zero 3: sbcs/orange-pi-zero-3.md
  - Radxa:
    - Radxa Nio 12L: sbcs/radxa-nio-12l.md
    - Radxa Rock 5A: sbcs/radxa-rock-5a.md
    - Radxa Rock 5B: sbcs/radxa-rock-5b.md
    - Radxa Zero 2: sbcs/radxa-zero-2.md
    - Radxa Zero: sbcs/radxa-zero.md
  - Raspberry Pi:
    - Raspberry Pi 2: sbcs/raspberry-pi-2.md
    - Raspberry Pi 3: sbcs/raspberry-pi-3.md
    - Raspberry Pi 400: sbcs/raspberry-pi-400.md
    - Raspberry Pi 4: sbcs/raspberry-pi-4.md
    - Raspberry Pi 5: sbcs/raspberry-pi-5.md
    - Raspberry Pi A/A+/B/B+: sbcs/raspberry-pi-a-a-b-b.md
    - Raspberry Pi Zero 2: sbcs/raspberry-pi-zero-2.md
    - Raspberry Pi Zero: sbcs/raspberry-pi-zero.md
  - StarFive VisionFive 2: sbcs/starfive-visionfive-2.md
- Handhelds:
  - Overview: handhelds/index.md
  - Catalog:
    - Anbernic:
      - Overview: handhelds/anbernic.md
      - Anbernic RG351: handhelds/anbernic/rg351pmv.md
      - Anbernic RG353: handhelds/anbernic/rg353pmvvs.md
      - Anbernic RG503: handhelds/anbernic/rg503.md
      - Anbernic RG552: handhelds/anbernic/rg552.md
      - Anbernic RG ARC: handhelds/anbernic/rgarc.md
      - Anbernic RG35XX Plus: handhelds/anbernic/rg35xx-plus.md
      - Anbernic RG35XX Pro: handhelds/anbernic/rg35xx-pro.md
      - Anbernic RG35XX 2024: handhelds/anbernic/rg35xx-2024.md
      - Anbernic RG35XX H: handhelds/anbernic/rg35xx-h.md
      - Anbernic RG35XX SP: handhelds/anbernic/rg35xx-sp.md
      - Anbernic RG28XX: handhelds/anbernic/rg28xx.md
      - Anbernic RG40XX V: handhelds/anbernic/rg40xx-v.md
      - Anbernic RG40XX H: handhelds/anbernic/rg40xx-h.md
      - Anbernic RG CubeXX: handhelds/anbernic/rg-cubexx.md
      - Anbernic RG34XX: handhelds/anbernic/rg34xx.md
    - Ayn:
      - Overview: handhelds/ayn.md
      - Ayn Odin 2: handhelds/ayn/odin2.md
    - AYANEO:
      - Overview: handhelds/ayaneo.md
      - Pocket S: handhelds/ayaneo/pockets.md
    - GameForce:
      - GameForce Chi: sbcs/gameforce-chi.md
      - GameForce Ace: handhelds/gameforce/gameforce-ace.md
    - Hardkernel:
      - Overview: handhelds/hardkernel.md
      - Odroid Go Advance: handhelds/hardkernel/odroid-go-advance.md
      - Odroid Go Super: handhelds/hardkernel/odroid-go-super.md
      - Odroid Go Ultra: handhelds/hardkernel/odroid-go-ultra.md
    - MagicX:
      - XU Mini M: handhelds/magicx/xu-mini-m.md
    - Powkiddy:
      - Overview: handhelds/powkiddy.md
      - RGB10: handhelds/powkiddy/rgb10.md
      - RGB10 Max 3 Pro: handhelds/powkiddy/rgb10-max-3-pro.md
      - RGB10 Max 3: handhelds/powkiddy/rgb10-max-3.md
      - RGB10X: handhelds/powkiddy/rgb10x.md
      - RK2023: handhelds/powkiddy/rk2023.md
      - RGB20SX: handhelds/powkiddy/rgb20sx.md
      - RGB20 Pro: handhelds/powkiddy/rgb20-pro.md
      - RGB30: handhelds/powkiddy/rgb30.md
      - X35S: handhelds/powkiddy/x35s.md
      - X35H: handhelds/powkiddy/x35h.md
      - X55: handhelds/powkiddy/x55.md
      - XU10: handhelds/powkiddy/xu10.md
    - Retroid:
      - Overview: handhelds/retroid.md
      - Retroid Pocket 5: handhelds/retroid/retroid-pocket-5.md
      - Retroid Pocket Mini: handhelds/retroid/retroid-pocket-mini.md
      - Retroid Pocket Flip2: handhelds/retroid/retroid-pocket-flip2.md
    - x86_64:
      - Asus ROG Ally: handhelds/x86_64/asus-rog-ally.md
      - Valve Steam Deck: handhelds/x86_64/steam-deck.md
    - Unbranded:
      - Game Console R33S: handhelds/unbranded/game-console-r33s.md
      - Game Console R35S R36S: handhelds/unbranded/game-console-r35s-r36s.md
      - RK3326 clones: handhelds/unbranded/rk3326-clones.md
- Emulators:
  - Overview: systems/index.md
  - Emulated Systems:
    - Apple:
      - Apple II: systems/apple2.md
      - Apple IIGS: systems/apple2gs.md
      - Macintosh: systems/macintosh.md
    - Atari:
      - Atari Lynx: systems/lynx.md
      - Atari 2600: systems/atari2600.md
      - Atari 5200: systems/atari5200.md
      - Atari 7800: systems/atari7800.md
      - Atari XE Game System: systems/xegs.md
      - Jaguar: systems/jaguar.md
      - Jaguar CD: systems/jaguarcd.md
      - Atari 800: systems/atari800.md
      - Atari ST: systems/atarist.md
    - Commodore:
      - Commodore VIC-20: systems/c20.md
      - Commodore 64: systems/c64.md
      - Commodore 128: systems/c128.md
      - Commodore Plus4: systems/cplus4.md
      - Commodore PET: systems/pet.md
      - Amiga:
        - Amiga AGA: systems/amiga1200.md
        - Amiga OCS/ECS: systems/amiga500.md
        - Amiga CD32: systems/amigacd32.md
        - Amiga CDTV: systems/amigacdtv.md
    - Microsoft:
      - MSX:
        - MSX1: systems/msx1.md
        - MSX2: systems/msx2.md
        - MSX2+: systems/msx2+.md
        - MSX Turbo-R: systems/msxturbor.md
      - Xbox: systems/xbox.md
      - Xbox 360: systems/xbox360.md
    - Nintendo:
      - Nintendo Entertainment System: systems/nes.md
      - Family Computer Disk System: systems/fds.md
      - Super Nintendo Entertainment System: systems/snes.md
      - Super Disc System (MSU1): systems/snes-msu1.md
      - Nintendo 64: systems/n64.md
      - Nintendo 64 Disk Drive: systems/n64dd.md
      - GameCube: systems/gamecube.md
      - Wii: systems/wii.md
      - Wii U: systems/wiiu.md
      - Switch: systems/switch.md
      - Game Boy: systems/gb.md
      - Virtual Boy: systems/virtualboy.md
      - Game Boy Color: systems/gbc.md
      - Game Boy Advance: systems/gba.md
      - Nintendo DS: systems/nds.md
      - 3DS: systems/3ds.md
    - NEC:
      - PC Engine: systems/pcengine.md
      - PC Engine CD: systems/pcenginecd.md
      - Supergrafx: systems/supergrafx.md
      - PC-FX: systems/pcfx.md
    - Sega:
      - SG-1000: systems/sg1000.md
      - Master System: systems/mastersystem.md
      - Game Gear: systems/gamegear.md
      - Mega Drive: systems/megadrive.md
      - Sega CD: systems/segacd.md
      - MSU-MD: systems/msu-md.md
      - 32x: systems/sega32x.md
      - Saturn: systems/saturn.md
      - Sega Pico: systems/pico.md
      - Dreamcast: systems/dreamcast.md
      - Dreamcast VMU: systems/vemulator.md
      - Model 3: systems/model3.md
      - Naomi: systems/naomi.md
      - Naomi 2: systems/naomi2.md
    - Sony:
      - PlayStation: systems/psx.md
      - PlayStation 2: systems/ps2.md
      - PlayStation 3: systems/ps3.md
      - PlayStation 4: systems/ps4.md
      - PlayStation Portable: systems/psp.md
      - PlayStation Vita: systems/psvita.md
    - SNK:
      - Neo-Geo: systems/neogeo.md
      - Neo-Geo CD: systems/neogeocd.md
      - Neo-Geo Pocket: systems/ngp.md
      - Neo-Geo Pocket Color: systems/ngpc.md
    - 3DO Interactive Multiplayer: systems/3do.md
    - ADAM: systems/adam.md
    - Adventure Vision: systems/advision.md
    - Amstrad CPC: systems/amstradcpc.md
    - M-1000: systems/apfm1000.md
    - Arcadia 2001: systems/arcadia.md
    - Archimedes: systems/archimedes.md
    - Arduboy: systems/arduboy.md
    - Astrocade: systems/astrocde.md
    - Atom: systems/atom.md
    - Atomiswave: systems/atomiswave.md
    - BBC Micro: systems/bbc.md
    - Camputers Lynx: systems/camplynx.md
    - CD-i: systems/cdi.md
    - Channel-F: systems/channelf.md
    - Sega Chihiro: systems/chihiro.md
    - Color Computer: systems/coco.md
    - ColecoVision: systems/colecovision.md
    - Commander X16: systems/commanderx16.md
    - CreatiVision: systems/crvision.md
    - Daphne: systems/daphne.md
    - Dos (x86): systems/dos.md
    - Electron: systems/electron.md
    - Final Burn Neo: systems/fbneo.md
    - Applications: systems/flatpak.md
    - FM-7: systems/fm7.md
    - FM-TOWNS: systems/fmtowns.md
    - Gamate: systems/gamate.md
    - Game and Watch: systems/gameandwatch.md
    - Game.com: systems/gamecom.md
    - Game Pocket Computer: systems/gamepock.md
    - Game Master: systems/gmaster.md
    - Pong: systems/gong.md
    - GP32: systems/gp32.md
    - GX4000: systems/gx4000.md
    - Mattel Intellivision: systems/intellivision.md
    - Java 2 MicroEdition: systems/j2me.md
    - Laser 310: systems/laser310.md
    - LCD Games: systems/lcdgames.md
    - Mame: systems/mame.md
    - Mega Duck / Cougar Boy: systems/megaduck.md
    - Moonlight Embedded: systems/moonlight.md
    - Othello Multivision: systems/multivision.md
    - Namco System 246/256: systems/namco2x6.md
    - N-Gage: systems/ngage.md
    - Odyssey2: systems/o2em.md
    - PC-8800: systems/pc88.md
    - PC-9800: systems/pc98.md
    - PDP-1: systems/pdp1.md
    - Plug and Play TV Games: systems/plugnplay.md
    - Pokemon Mini: systems/pokemini.md
    - PV-1000: systems/pv1000.md
    - "SAM Coup\xE9": systems/samcoupe.md
    - Satellaview: systems/satellaview.md
    - Super Cassette Vision: systems/scv.md
    - Super Game Boy: systems/sgb.md
    - Socrates: systems/socrates.md
    - Spectravideo SV-328: systems/spectravideo.md
    - Steam: systems/steam.md
    - SuFami Turbo: systems/sufami.md
    - Supervision: systems/supervision.md
    - Super A'Can: systems/supracan.md
    - Sega System SP: systems/systemsp.md
    - Thomson - MO/TO (Theodore): systems/thomson.md
    - TI-99: systems/ti99.md
    - Triforce: systems/triforce.md
    - Tutor: systems/tutor.md
    - Uzebox: systems/uzebox.md
    - VC 4000: systems/vc4000.md
    - Vectrex: systems/vectrex.md
    - Videopac+ G7400: systems/videopacplus.md
    - Tandy Video Information System: systems/vis.md
    - Visual Pinball X: systems/vpinball.md
    - V.Smile: systems/vsmile.md
    - WonderSwan: systems/wswan.md
    - WonderSwan Color: systems/wswanc.md
    - Sharp X1: systems/x1.md
    - Sharp X68000: systems/x68000.md
    - Zelda Classic: systems/zc210.md
    - ZX81: systems/zx81.md
    - ZX Spectrum: systems/zxspectrum.md
- Ports:
  - Overview: ports/index.md
  - Game ports:
    - Cannonball: ports/cannonball.md
    - Cave Story: ports/cavestory.md
    - Commander Genius: ports/cgenius.md
    - CorsixTH: ports/corsixth.md
    - DevilutionX: ports/devilutionx.md
    - Doom 3: ports/doom3.md
    - DXX Rebirth: ports/dxx-rebirth.md
    - ECWolf: ports/ecwolf.md
    - EDuke32: ports/eduke32.md
    - Wolfenstein - Enemy Territory: ports/etlegacy.md
    - Fallout Community Edition: ports/fallout1-ce.md
    - Fallout 2 Community Edition: ports/fallout2-ce.md
    - Ion Fury: ports/fury.md
    - GZDoom: ports/gzdoom.md
    - Return To Castle Wolfenstein: ports/iortcw.md
    - Jazz Jackrabbit 2: ports/jazz2.md
    - MrBoom: ports/mrboom.md
    - Jazz Jackrabbit: ports/openjazz.md
    - OpenLara: ports/openlara.md
    - PrBoom: ports/prboom.md
    - Quake III: ports/quake3.md
    - Raze: ports/raze.md
    - REminiscence: ports/reminiscence.md
    - Rise of the Triad: ports/rott.md
    - SdlPop: ports/sdlpop.md
    - Sonic Mania: ports/sonic-mania.md
    - Sonic 3 A.I.R.: ports/sonic3-air.md
    - Sonic Retro Engine: ports/sonicretro.md
    - The Force Engine: ports/theforceengine.md
    - TyrQuake: ports/tyrquake.md
    - Ur-Quan Masters: ports/uqm.md
    - Quake II: ports/vitaquake2.md
    - Xash3D-FWGS: ports/xash3d_fwgs.md
    - xrick: ports/xrick.md
- Engines:
  - Overview: engines/index.md
  - Supported Engines:
    - EasyRPG: engines/easyrpg.md
    - Flash Player: engines/flash.md
    - IKEMEN: engines/ikemen.md
    - OpenBOR: engines/openbor.md
    - Solarus: engines/solarus.md
    - Singe: engines/singe.md
    - ScummVM: engines/scummvm.md
    - TheXTech: engines/thextech.md
  - Games:
    - Abuse: games/abuse.md
    - C-Dogs SDL: games/cdogs.md
    - Hydra Castle Labyrinth: games/hcl.md
    - Hurrican: games/hurrican.md
    - Super Mario War: games/superbroswar.md
    - Tyrian: games/tyrian.md
- Installation: installation.md
- Developer Guide: dev-guide.md
- Community: community.md
plugins:
- search
- git-revision-date-localized
markdown_extensions:
- admonition
- codehilite
- toc:
    permalink: true
- footnotes
extra_css:
  - assets/reglinux-theme.css
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/REG-Linux
  - icon: fontawesome/brands/discord
    link: https://discord.gg/reglinux
